[package]
name = "ghl-syntax"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Lexer, AST and Parser for GHL"

[dependencies]
ghl-diagnostics = { path = "../ghl-diagnostics" }
logos = "0.14"
chumsky = { version = "0.9", default-features = false, features = ["ahash", "std"] }

