//! Phase 1 (`benchmarks/suites/02`, Case 2.1) — compares the legacy CSV parser
//! (`parse_csv_string`, single-threaded, used today only by `parse_csv()` on text in
//! memory) against the new `read_csv_file` (multithreaded polars-io for tokenization +
//! GHL type inference / `NA:reason` preservation), tested on a file generated by
//! `generate_synthetic_csv` with real benchmark measurements.
//!
//! Usage: `cargo run --release --example spike_csv_ingest_latency -p ghl-runtime -- <csv_path>`

use ghl_runtime::io::{parse_csv_string, read_csv_file, read_file};
use std::time::Instant;

fn height_of(df: &ghl_runtime::Value) -> usize {
    match df {
        ghl_runtime::Value::DataFrame { frame, .. } => frame.height(),
        _ => 0,
    }
}

fn report(label: &str, size_mb: f64, height: usize, elapsed: std::time::Duration) {
    let throughput_mb_s = size_mb / elapsed.as_secs_f64();
    let rows_per_sec = height as f64 / elapsed.as_secs_f64();
    println!("\n[{label}] {height} rows in {elapsed:.2?}");
    println!("[{label}] Throughput: {throughput_mb_s:.1} MB/s, {rows_per_sec:.0} rows/s");
    if height > 0 {
        let projected_25m = elapsed.as_secs_f64() * (25_000_000.0 / height as f64);
        println!(
            "[{label}] Linear projection to 25M rows: ~{:.1} min",
            projected_25m / 60.0
        );
    }
}

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let path = args
        .get(1)
        .cloned()
        .unwrap_or_else(|| "target/synthetic.csv".to_string());

    let content = read_file(&path).unwrap_or_else(|e| {
        eprintln!("Could not read {path}: {e:?}");
        eprintln!("Generate it first with: cargo run --release --example generate_synthetic_csv -p ghl-runtime -- <rows> {path}");
        std::process::exit(1);
    });
    let size_mb = content.len() as f64 / (1024.0 * 1024.0);
    let num_lines = content.lines().count().saturating_sub(1);
    println!("File: {path} ({size_mb:.1} MB, ~{num_lines} rows)");

    println!("\n== parse_csv_string (legacy, single-thread) ==");
    let start = Instant::now();
    let df_old = parse_csv_string(&content, None).expect("old CSV parse should succeed");
    report("legacy", size_mb, height_of(&df_old), start.elapsed());

    println!("\n== read_csv_file (new, multithreaded polars-io + GHL inference) ==");
    let start = Instant::now();
    let df_new = read_csv_file(&path, None).expect("new CSV read should succeed");
    report("new", size_mb, height_of(&df_new), start.elapsed());
}
